name: ardimedia
favicon: null
layout_spectrum: 0.3857800494879484
typography_spectrum: 0.4048052290454507
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.02555310120806098
  lightness: 0.8640075263101608
  saturation: 0.8501264755614102
  rhythmicContrast: 0.35419884719885886
purpose: []
